name: Deploy to Render

on:
  push:
    branches:
      - main   # or whichever branch you want

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render build
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d2te50ruibrs73enb51g?key=PIygNEugOaY"
